### PR TITLE
Unify units

### PR DESCRIPTION
**Pull request by mhochsteger**
Tasks:
- [x] Read proper unit and quantity values for spar articles
    possible units: g, m, ml, stk, wg  (m... Meter, wg ... Waschgänge)
- [x] ~~Search input for Quantity (allows integer numbers, searches for exact match)~~
- [x]  ~~Extra column in table~~
- [x] Unit/quantity for Hofer
- [x] Unit/quantity for Billa
- [x]  MPreis
- [x]  Lidl
- [x]  DM

@badlogic The search input was just for testing, have no Idea what exactly you had in mind.

### CODE REVIEW

**Comment by badlogic** [comment]
I'm not yet sure how to handle all this. For Hofer, the unit property is really the quantity plus packaging. Most items have the actual content unit in their name. E.g.

Screenshot 2023-05-20 at 14 45 38

I haven't checked how Hofer encodes weighted items yet. I'm not sure they actually have those apart from fruit?

The other PR of yours that I merged yesterday also requires regenerating the `latest-canonical.json` file from historical data via `replay()` in `analysis.js`. I'm not yet fully sure if going with the 1 KG price for things like cheese or sausage is the way to go. From a user perspective, 100g is usually the unit you're interested in, which is also the unit you'll see in stores.

I'm currently compiling a list of units for each store. Based on that, we can then try to normalize the `unit` field in the canonical items, and allow that in searches. We may also want to normalize `.` and `,` in item names, e.g. milk may have `3.6% Fett` in one store and `3,6% Fett` in another.

I'll post the unit lists for each store here later today.

**Comment by badlogic** [comment]
In Billa's case, it appears the prices for weighted sausage are also given per KG, but the `grammage` field in the originald data is `per 100g`

Screenshot 2023-05-20 at 15 14 42

**Comment by badlogic** [comment]
Billa has `grammagePriceFactor` for weighted cheeses and sausages. I'll modify `billaToCanonical` analogously to `sparToCanonical` so those are comparable.

**Comment by badlogic** [comment]
Regarding search, I think it makes more sense to have a single search field where the user can enter both the product name(-parts) and any units they are interested in. That's how it currently works, however, since the units haven't been unified yet, that search may fail.

**Comment by mhochsteger** [comment]
Did a rebase on upstream and parsing for Hofer and Billa. I think the data looks good now.
@badlogic could you have a look?

Currently, the data is always presented in `g/ml/stk`. We can of course convert it to `l/kg` for larger numbers. Do you really want an extra field for that, or just convert it on the client side?

Calculating price per 100 g/ml is also easy now on the client side.

**Comment by mhochsteger** [comment]
FYI: Also started to work on lidl

**Comment by mhochsteger** [comment]
I added a field "isWeighted" (currently only in mpreis articles) and fixed the pricing for such articles (see #24).
Let me know if you want an extra MR for that (or just do cherry-picking).

**Comment by mhochsteger** [comment]
Converts now all weighted articles to 100g/ml (separate utility function in store/utils.js).
Also shows a scale for weighted items.
DeepinScreenshot_select-area_20230528195244

Anyway, showing 0.18 Euro per 100g for Apples seems odd too to me. Maybe just use 100g as baseline when the price is above a certain value?

Also, I guess this conversion needs a replay to also scale historical values.

**Comment by badlogic** [comment]
I think it's good to go as is, we can iterate (and replay) any time we think a change is needed. I'll merge this tonight (I hope).

**Comment by badlogic** [comment]
> Currently, the data is always presented in g/ml/stk. We can of course convert it to l/kg for larger numbers. Do you really want an extra field for that, or just convert it on the client side?

You're right, g/ml/stk is all we need. Anything >= say 1000ml can be presented as liter client side.

**Comment by mhochsteger** [comment]
Conversion into kg/l was already done, I just merged main and resolved the conflicts. From my side it's ready to go :)

**Comment by badlogic** [comment]
Screenshot 2023-05-29 at 01 09 00

Haven't dug into it yet, but i think mpreis ingestion is wonky irrespective of units?

**Comment by badlogic** [comment]
Screenshot 2023-05-29 at 01 13 31

**Comment by mhochsteger** [comment]
There are 3 prices in the mpreis data, sometimes one of them has H87 as unit, I mistake ly i terpreted that as liter. In this case, we need to read the unit from another price.
I can fix this later today.

On May 29, 2023 1:13:51 AM GMT+02:00, Mario Zechner ***@***.***> wrote:
>Screenshot 2023-05-29 at 01 13 31
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/badlogic/heissepreise/pull/10#issuecomment-1566297892
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
