### PR TITLE
New Billa Onlinestore

### PR DESCRIPTION
**Pull request by flobauer**
WORK IN PROGRESS!

### CODE REVIEW

**Comment by flobauer** [comment]
This is work in progress, I would like first to check with @badlogic if direction makes sense.

-> with this method I get 15811 products via the API.

Open: 
- how to map categories
- do we need to worry about subcategories 
- do we map products
- is data missing in the new API

**Comment by flobauer** [comment]
Ok, when I remove duplicates there are products in multiple categories: New Count is 11842

**Comment by badlogic** [comment]
Looked into it last night. I think it's better to hardcode the category slugs (they don't change for the top level) instead of going through the letters of the alphabet.

Then just fetch all products per category through the respective api and deduplicate.

**Comment by flobauer** [comment]
I added the category list I was able to find so far with slugs to `stores/billa-categories.json`

**Comment by flobauer** [comment]
I adapted the product structure, but I have difficulties to standardise the quantity amounts.

**Comment by frocentus** [comment]
Ich hab das auch grad mit der einem Powershell-Script nachvollzogen, ich komme auch genau auf 11993 Produkte, die Anzahl in den Kategorien passt nicht zu der Anzahl die man in der tatsächlichen Kategorie rausbekommt.

**Comment by badlogic** [comment]
That's about as many as we have from the old data (which also contains
unavailable products since 2017). Some products are in multiple categories,
which is why they need to be deduplicated.

**Comment by mhochsteger** [comment]
> I adapted the product structure, but I have difficulties to standardise the quantity amounts.

I will have a look at the quantities.

**Comment by badlogic** [comment]
I'm looking into ensuring the new data is consistent with the old one, so we don't destroy the historic pricing data.

**Comment by mhochsteger** [comment]
Made some progress (and a separate PR #166). Data is not consistent yet (and the prices seem to be wrong). I'm on it.

**Comment by badlogic** [comment]
@mhochsteger @flobauer I've rewritten this PR as it wasn't robust in light of product and category additions. My rewrite also cleanly maps categories. I'm lacking a `getCanonical()` implementation still.

@flobauer thanks for the initial work! I'm closing this out.
@mhochsteger I'll be incorporating your PRs work as well.

**Comment by badlogic** [comment]
All fixed, danke für die Hilfe!

**Pull request closed without merging**
