### PR TITLE
Fetch canonical compressed in parallel

### PR DESCRIPTION
**Pull request by iantsch**
Further improvement of #34

### CODE REVIEW

**Comment by badlogic** [comment]
Now we'll see if SSL handshake overhead per requests kills this :D

**Comment by iantsch** [comment]
http1 might need a keep-alive header
http2 should handle it AFAIK

**Comment by badlogic** [comment]
My server config is bad and I should feel bad :(

Screenshot 2023-05-30 at 13 59 39

Also, each stores file size varies heavily, which diminishes the returns. Equally sized files would probably help quite a bit.

Overall, with my shitty server config, this is a net loss. I'm tempted to revert it :p

**Comment by badlogic** [comment]
Screenshot 2023-05-30 at 14 04 40

Welp. Unfucking my server config is a lot of work.

**Comment by iantsch** [comment]
I will see a revert I guess 😂

**Comment by badlogic** [comment]
Please don't hate me. That's what you get for working on spaghetti OSS!

**Comment by iantsch** [comment]
Try setting the keep-alive headers in the index.js
```js
  const server = app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
  });
  server.keepAliveTimeout = 30 * 1000;
  server.headersTimeout = 35 * 1000;
```

**Comment by badlogic** [comment]
I'm not using the Express server in that deployment. I just serve static
files through Nginx, which itself is behind a reverse proxy. Which makes it
even more hilarious how slow it is. I'll figure it out on my end, let's
keep the change.

**Comment by iantsch** [comment]
in that case you should definitely use http2 and push the assets from the server to increase the speed 😆 

```nginx
server {
  listen 443 ssl http2;

  location /index.html {
    http2_push /styles.css;
    http2_push /utils.js;
    http2_push /latest-caninical.billa.compressed.json;
    http2_push /latest-caninical.dm.compressed.json;
    http2_push /latest-caninical.hofer.compressed.json;
    http2_push /latest-caninical.lidl.compressed.json;
    http2_push /latest-caninical.mpreis.compressed.json;
    http2_push /latest-caninical.spar.compressed.json;
    http2_push /latest-caninical.unimarkt.compressed.json;
    http2_push /alasql.js;
    http2_push /chart.js;
    http2_push /main.js;
  }
}
```

**Pull request merged**
