### PR TITLE
Add Müller Austria and Müller Germany without categorization

### PR DESCRIPTION
**Pull request by tiefenb**
* Added mueller.at and mueller.de (mueller.ch would be that easy but not euro values)
* no categorization (I can add this soon)
* excluded some categories which are non-food or non-Drogerie: "Spielwaren", "Multi-Media", "Schreibwaren", "Strümpfe", "Handarbeit", "Bücher"]
* I used some still existing colors for the store - maybe you find some better colors

### CODE REVIEW

**Comment by badlogic** [comment]
Nice!

**Comment by badlogic** [comment]
Hrm, Müller has started to fail for me.

```
Error while fetching data from mueller, continuing after 21.86838447570801 seconds... AxiosError: Request failed with status code 404
hp_site |     at settle (/heisse-preise/node_modules/axios/dist/node/axios.cjs:1909:12)
hp_site |     at Unzip.handleStreamEnd (/heisse-preise/node_modules/axios/dist/node/axios.cjs:2989:11)
hp_site |     at Unzip.emit (node:events:525:35)
hp_site |     at endReadableNT (node:internal/streams/readable:1359:12)
hp_site |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
hp_site |   code: 'ERR_BAD_REQUEST',
hp_site |   config: {
hp_site |     transitional: {
hp_site |       silentJSONParsing: true,
hp_site |       forcedJSONParsing: true,
hp_site |       clarifyTimeoutError: false
hp_site |     },
hp_site |     adapter: [ 'xhr', 'http' ],
hp_site |     transformRequest: [ [Function: transformRequest] ],
hp_site |     transformResponse: [ [Function: transformResponse] ],
hp_site |     timeout: 0,
hp_site |     xsrfCookieName: 'XSRF-TOKEN',
hp_site |     xsrfHeaderName: 'X-XSRF-TOKEN',
hp_site |     maxContentLength: -1,
hp_site |     maxBodyLength: -1,
hp_site |     env: { FormData: [Function], Blob: [class Blob] },
hp_site |     validateStatus: [Function: validateStatus],
hp_site |     headers: AxiosHeaders {
hp_site |       Accept: 'application/json, text/plain, */*',
hp_site |       'User-Agent': 'axios/1.4.0',
hp_site |       'Accept-Encoding': 'gzip, compress, deflate, br'
hp_site |     },
hp_site |     method: 'get',
hp_site |     url: 'https://www.mueller.at/genusswelt/aktionen/?ajax=true&p=1',
hp_site |     data: undefined
hp_site |   },
hp_site |   request: <ref *1> ClientRequest {
hp_site |     _events: [Object: null prototype] {
hp_site |       abort: [Function (anonymous)],
hp_site |       aborted: [Function (anonymous)],
hp_site |       connect: [Function (anonymous)],
hp_site |       error: [Function (anonymous)],
hp_site |       socket: [Function (anonymous)],
hp_site |       timeout: [Function (anonymous)],
hp_site |       finish: [Function: requestOnFinish]
hp_site |     },
hp_site |     _eventsCount: 7,
hp_site |     _maxListeners: undefined,
hp_site |     outputData: [],
hp_site |     outputSize: 0,
hp_site |     writable: true,
hp_site |     destroyed: true,
hp_site |     _last: true,
hp_site |     chunkedEncoding: false,
hp_site |     shouldKeepAlive: true,
hp_site |     maxRequestsOnConnectionReached: false,
hp_site |     _defaultKeepAlive: true,
hp_site |     useChunkedEncodingByDefault: false,
hp_site |     sendDate: false,
hp_site |     _removedConnection: false,
hp_site |     _removedContLen: false,
hp_site |     _removedTE: false,
hp_site |     strictContentLength: false,
hp_site |     _contentLength: 0,
hp_site |     _hasBody: true,
hp_site |     _trailer: '',
hp_site |     finished: true,
hp_site |     _headerSent: true,
hp_site |     _closed: true,
hp_site |     socket: TLSSocket {
hp_site |       _tlsOptions: [Object],
hp_site |       _secureEstablished: true,
hp_site |       _securePending: false,
hp_site |       _newSessionPending: false,
hp_site |       _controlReleased: true,
hp_site |       secureConnecting: false,
hp_site |       _SNICallback: null,
hp_site |       servername: 'www.mueller.at',
hp_site |       alpnProtocol: false,
hp_site |       authorized: true,
hp_site |       authorizationError: null,
hp_site |       encrypted: true,
hp_site |       _events: [Object: null prototype],
hp_site |       _eventsCount: 9,
hp_site |       connecting: false,
hp_site |       _hadError: false,
hp_site |       _parent: null,
hp_site |       _host: 'www.mueller.at',
hp_site |       _closeAfterHandlingError: false,
hp_site |       _readableState: [ReadableState],
hp_site |       _maxListeners: undefined,
hp_site |       _writableState: [WritableState],
hp_site |       allowHalfOpen: false,
hp_site |       _sockname: null,
hp_site |       _pendingData: null,
hp_site |       _pendingEncoding: '',
hp_site |       server: undefined,
hp_site |       _server: null,
hp_site |       ssl: [TLSWrap],
hp_site |       _requestCert: true,
hp_site |       _rejectUnauthorized: true,
hp_site |       timeout: 5000,
hp_site |       parser: null,
hp_site |       _httpMessage: null,
hp_site |       [Symbol(res)]: [TLSWrap],
hp_site |       [Symbol(verified)]: true,
hp_site |       [Symbol(pendingSession)]: null,
hp_site |       [Symbol(async_id_symbol)]: -1,
hp_site |       [Symbol(kHandle)]: [TLSWrap],
hp_site |       [Symbol(lastWriteQueueSize)]: 0,
hp_site |       [Symbol(timeout)]: Timeout {
hp_site |         _idleTimeout: 5000,
hp_site |         _idlePrev: [TimersList],
hp_site |         _idleNext: [Timeout],
hp_site |         _idleStart: 26080,
hp_site |         _onTimeout: [Function: bound ],
hp_site |         _timerArgs: undefined,
hp_site |         _repeat: null,
hp_site |         _destroyed: false,
hp_site |         [Symbol(refed)]: false,
hp_site |         [Symbol(kHasPrimitive)]: false,
hp_site |         [Symbol(asyncId)]: 61936,
hp_site |         [Symbol(triggerId)]: 61934
hp_site |       },
hp_site |       [Symbol(kBuffer)]: null,
hp_site |       [Symbol(kBufferCb)]: null,
hp_site |       [Symbol(kBufferGen)]: null,
hp_site |       [Symbol(kCapture)]: false,
hp_site |       [Symbol(kSetNoDelay)]: false,
hp_site |       [Symbol(kSetKeepAlive)]: true,
hp_site |       [Symbol(kSetKeepAliveInitialDelay)]: 1,
hp_site |       [Symbol(kBytesRead)]: 0,
hp_site |       [Symbol(kBytesWritten)]: 0,
hp_site |       [Symbol(connect-options)]: [Object]
hp_site |     },
hp_site |     _header: 'GET /genusswelt/aktionen/?ajax=true&p=1 HTTP/1.1\r\n' +
hp_site |       'Accept: application/json, text/plain, */*\r\n' +
hp_site |       'User-Agent: axios/1.4.0\r\n' +
hp_site |       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
hp_site |       'Host: www.mueller.at\r\n' +
hp_site |       'Connection: keep-alive\r\n' +
hp_site |       '\r\n',
hp_site |     _keepAliveTimeout: 0,
hp_site |     _onPendingData: [Function: nop],
hp_site |     agent: Agent {
hp_site |       _events: [Object: null prototype],
hp_site |       _eventsCount: 2,
hp_site |       _maxListeners: undefined,
hp_site |       defaultPort: 443,
hp_site |       protocol: 'https:',
hp_site |       options: [Object: null prototype],
hp_site |       requests: [Object: null prototype] {},
hp_site |       sockets: [Object: null prototype],
hp_site |       freeSockets: [Object: null prototype],
hp_site |       keepAliveMsecs: 1000,
hp_site |       keepAlive: true,
hp_site |       maxSockets: Infinity,
hp_site |       maxFreeSockets: 256,
hp_site |       scheduling: 'lifo',
hp_site |       maxTotalSockets: Infinity,
hp_site |       totalSocketCount: 8,
hp_site |       maxCachedSessions: 100,
hp_site |       _sessionCache: [Object],
hp_site |       [Symbol(kCapture)]: false
hp_site |     },
hp_site |     socketPath: undefined,
hp_site |     method: 'GET',
hp_site |     maxHeaderSize: undefined,
hp_site |     insecureHTTPParser: undefined,
hp_site |     joinDuplicateHeaders: undefined,
hp_site |     path: '/genusswelt/aktionen/?ajax=true&p=1',
hp_site |     _ended: true,
hp_site |     res: IncomingMessage {
hp_site |       _readableState: [ReadableState],
hp_site |       _events: [Object: null prototype],
hp_site |       _eventsCount: 4,
hp_site |       _maxListeners: undefined,
hp_site |       socket: null,
hp_site |       httpVersionMajor: 1,
hp_site |       httpVersionMinor: 1,
hp_site |       httpVersion: '1.1',
hp_site |       complete: true,
hp_site |       rawHeaders: [Array],
hp_site |       rawTrailers: [],
hp_site |       joinDuplicateHeaders: undefined,
hp_site |       aborted: false,
hp_site |       upgrade: false,
hp_site |       url: '',
hp_site |       method: null,
hp_site |       statusCode: 404,
hp_site |       statusMessage: 'Not Found',
hp_site |       client: [TLSSocket],
hp_site |       _consuming: true,
hp_site |       _dumped: false,
hp_site |       req: [Circular *1],
hp_site |       responseUrl: 'https://www.mueller.at/genusswelt/aktionen/?ajax=true&p=1',
hp_site |       redirects: [],
hp_site |       [Symbol(kCapture)]: false,
hp_site |       [Symbol(kHeaders)]: [Object],
hp_site |       [Symbol(kHeadersCount)]: 40,
hp_site |       [Symbol(kTrailers)]: null,
hp_site |       [Symbol(kTrailersCount)]: 0
hp_site |     },
hp_site |     aborted: false,
hp_site |     timeoutCb: null,
hp_site |     upgradeOrConnect: false,
hp_site |     parser: null,
hp_site |     maxHeadersCount: null,
hp_site |     reusedSocket: true,
hp_site |     host: 'www.mueller.at',
hp_site |     protocol: 'https:',
hp_site |     _redirectable: Writable {
hp_site |       _writableState: [WritableState],
hp_site |       _events: [Object: null prototype],
hp_site |       _eventsCount: 3,
hp_site |       _maxListeners: undefined,
hp_site |       _options: [Object],
hp_site |       _ended: true,
hp_site |       _ending: true,
hp_site |       _redirectCount: 0,
hp_site |       _redirects: [],
hp_site |       _requestBodyLength: 0,
hp_site |       _requestBodyBuffers: [],
hp_site |       _onNativeResponse: [Function (anonymous)],
hp_site |       _currentRequest: [Circular *1],
hp_site |       _currentUrl: 'https://www.mueller.at/genusswelt/aktionen/?ajax=true&p=1',
hp_site |       [Symbol(kCapture)]: false
hp_site |     },
hp_site |     [Symbol(kCapture)]: false,
hp_site |     [Symbol(kBytesWritten)]: 0,
hp_site |     [Symbol(kNeedDrain)]: false,
hp_site |     [Symbol(corked)]: 0,
hp_site |     [Symbol(kOutHeaders)]: [Object: null prototype] {
hp_site |       accept: [Array],
hp_site |       'user-agent': [Array],
hp_site |       'accept-encoding': [Array],
hp_site |       host: [Array]
hp_site |     },
hp_site |     [Symbol(errored)]: null,
hp_site |     [Symbol(kHighWaterMark)]: 16384,
hp_site |     [Symbol(kUniqueHeaders)]: null
hp_site |   },
hp_site |   response: {
hp_site |     status: 404,
hp_site |     statusText: 'Not Found',
hp_site |     headers: AxiosHeaders {
hp_site |       date: 'Thu, 29 Jun 2023 15:06:27 GMT',
hp_site |       'content-type': 'text/html;charset=UTF-8',
hp_site |       'transfer-encoding': 'chunked',
hp_site |       'x-request-id': '112b4cd0-69f7-3d75-b74c-1563942a36bb',
hp_site |       'set-cookie': [Array],
hp_site |       'x-content-type-options': 'nosniff',
hp_site |       'x-xss-protection': '1; mode=block',
hp_site |       'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
hp_site |       pragma: 'no-cache',
hp_site |       expires: '0',
hp_site |       'strict-transport-security': 'max-age=31536000 ; includeSubDomains, max-age=31536000; includeSubDomains',
hp_site |       'x-frame-options': 'SAMEORIGIN',
hp_site |       'x-powered-by': 'novomind iSHOP',
hp_site |       'content-security-policy': "base-uri 'self'; object-src 'none'; frame-ancestors 'self';",
hp_site |       'permissions-policy': 'accelerometer=(), ambient-light-sensor=(), autoplay=(self), battery=(), camera=(), cross-origin-isolated=(self), display-capture=(self), document-domain=(), encrypted-media=(self), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self), geolocation=*, gyroscope=(), magnetometer=(), microphone=(), midi=(), navigation-override=(self), payment=*, picture-in-picture=*, publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=*, usb=(), web-share=(), xr-spatial-tracking=(self)',
hp_site |       vary: 'accept-encoding',
hp_site |       'content-language': 'de',
hp_site |       server: 'nginx'
hp_site |     },
hp_site |     config: {
hp_site |       transitional: [Object],
hp_site |       adapter: [Array],
hp_site |       transformRequest: [Array],
hp_site |       transformResponse: [Array],
hp_site |       timeout: 0,
hp_site |       xsrfCookieName: 'XSRF-TOKEN',
hp_site |       xsrfHeaderName: 'X-XSRF-TOKEN',
hp_site |       maxContentLength: -1,
hp_site |       maxBodyLength: -1,
hp_site |       env: [Object],
hp_site |       validateStatus: [Function: validateStatus],
hp_site |       headers: [AxiosHeaders],
hp_site |       method: 'get',
hp_site |       url: 'https://www.mueller.at/genusswelt/aktionen/?ajax=true&p=1',
hp_site |       data: undefined
hp_site |     },
hp_site |     request: <ref *1> ClientRequest {
hp_site |       _events: [Object: null prototype],
hp_site |       _eventsCount: 7,
hp_site |       _maxListeners: undefined,
hp_site |       outputData: [],
hp_site |       outputSize: 0,
hp_site |       writable: true,
hp_site |       destroyed: true,
hp_site |       _last: true,
hp_site |       chunkedEncoding: false,
hp_site |       shouldKeepAlive: true,
hp_site |       maxRequestsOnConnectionReached: false,
hp_site |       _defaultKeepAlive: true,
hp_site |       useChunkedEncodingByDefault: false,
hp_site |       sendDate: false,
hp_site |       _removedConnection: false,
hp_site |       _removedContLen: false,
hp_site |       _removedTE: false,
hp_site |       strictContentLength: false,
hp_site |       _contentLength: 0,
hp_site |       _hasBody: true,
hp_site |       _trailer: '',
hp_site |       finished: true,
hp_site |       _headerSent: true,
hp_site |       _closed: true,
hp_site |       socket: [TLSSocket],
hp_site |       _header: 'GET /genusswelt/aktionen/?ajax=true&p=1 HTTP/1.1\r\n' +
hp_site |         'Accept: application/json, text/plain, */*\r\n' +
hp_site |         'User-Agent: axios/1.4.0\r\n' +
hp_site |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
hp_site |         'Host: www.mueller.at\r\n' +
hp_site |         'Connection: keep-alive\r\n' +
hp_site |         '\r\n',
hp_site |       _keepAliveTimeout: 0,
hp_site |       _onPendingData: [Function: nop],
hp_site |       agent: [Agent],
hp_site |       socketPath: undefined,
hp_site |       method: 'GET',
hp_site |       maxHeaderSize: undefined,
hp_site |       insecureHTTPParser: undefined,
hp_site |       joinDuplicateHeaders: undefined,
hp_site |       path: '/genusswelt/aktionen/?ajax=true&p=1',
hp_site |       _ended: true,
hp_site |       res: [IncomingMessage],
hp_site |       aborted: false,
hp_site |       timeoutCb: null,
hp_site |       upgradeOrConnect: false,
hp_site |       parser: null,
hp_site |       maxHeadersCount: null,
hp_site |       reusedSocket: true,
hp_site |       host: 'www.mueller.at',
hp_site |       protocol: 'https:',
hp_site |       _redirectable: [Writable],
hp_site |       [Symbol(kCapture)]: false,
hp_site |       [Symbol(kBytesWritten)]: 0,
hp_site |       [Symbol(kNeedDrain)]: false,
hp_site |       [Symbol(corked)]: 0,
hp_site |       [Symbol(kOutHeaders)]: [Object: null prototype],
hp_site |       [Symbol(errored)]: null,
hp_site |       [Symbol(kHighWaterMark)]: 16384,
hp_site |       [Symbol(kUniqueHeaders)]: null
hp_site |     },
hp_site |     data: '<!doctype html>\n' +
hp_site |       '<html>\n' +
hp_site |       '  <head>\n' +
hp_site |       '    <meta http-equiv="Content-type" content="text/html; charset=utf-8">\n' +
hp_site |       '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>\n' +
hp_site |       '    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n' +
hp_site |       '    <meta http-equiv="cleartype" content="on">\n' +
hp_site |       '    <title>404</title>\n' +
hp_site |       '    <link rel="stylesheet" href="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/css/critical.css">\n' +
hp_site |       '    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:wght@400;500;600&display=swap">\n' +
hp_site |       `    <link rel="stylesheet" media="print" href="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/css/app.css" onload="this.onload=null;this.media='all'">\n` +
hp_site |       '    <link rel="shortcut icon" type="image/x-icon" href="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/favicon.ico">\n' +
hp_site |       '    <link rel="icon" type="image/x-icon" href="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/favicon.ico">\n' +
hp_site |       '    <!-- Usercentrics -->\n' +
hp_site |       '<link rel="preconnect" href="//privacy-proxy.usercentrics.eu">\n' +
hp_site |       '  <link rel="preload" href="//privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js" as="script">\n' +
hp_site |       '  <script type="application/javascript" src="https://privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js"></script>\n' +
hp_site |       '<script id="usercentrics-cmp" src="https://app.usercentrics.eu/browser-ui/latest/loader.js" data-settings-id="DwYUgASxJ" async></script>\n' +
hp_site |       '      <script>\n' +
hp_site |       '  // Disable Usercentrics on following URLs\n' +
hp_site |       '  var disabledUrls = [\n' +
hp_site |       '    // DE/AT/CH\n' +
hp_site |       "    '/unternehmen/datenschutz/',\n" +
hp_site |       "    '/unternehmen/impressum/',\n" +
hp_site |       '    // ES\n' +
hp_site |       "    '/empresa/informacion-legal/',\n" +
hp_site |       "    '/empresa/impressum/',\n" +
hp_site |       '    // HR\n' +
hp_site |       "    '/tvrtka/zastita-privatnosti/',\n" +
hp_site |       "    '/tvrtka/impresum/',\n" +
hp_site |       '    // HU\n' +
hp_site |       "    '/vallalat/adatvedelem/',\n" +
hp_site |       "    '/vallalat/impresszum/',\n" +
hp_site |       '    // SI\n' +
hp_site |       "    '/o-podjetju/varstvo-osebnih-podatkov/',\n" +
hp_site |       '  ].filter(function (url) {\n' +
hp_site |       '    return location.href.indexOf(url) > 0;\n' +
hp_site |       '  });\n' +
hp_site |       '\n' +
hp_site |       '  if (disabledUrls.length > 0) {\n' +
hp_site |       '    window.UC_UI_SUPPRESS_CMP_DISPLAY = true;\n' +
hp_site |       '  }\n' +
hp_site |       '\n' +
hp_site |       "  // Attach opening Usercentrics' layer to the links\n" +
hp_site |       "  document.addEventListener('DOMContentLoaded', function () {\n" +
hp_site |       `    var links = document.querySelectorAll('a[href="#uc-central-modal-show"]');\n` +
hp_site |       '\n' +
hp_site |       '    for (var i = 0; i < links.length; i++) {\n' +
hp_site |       "      links[i].addEventListener('click', function (event) {\n" +
hp_site |       '        event.preventDefault();\n' +
hp_site |       '        UC_UI.showSecondLayer();\n' +
hp_site |       '      });\n' +
hp_site |       '    }\n' +
hp_site |       '  });\n' +
hp_site |       '\n' +
hp_site |       '  const createBVMeta = function() {\n' +
hp_site |       '    // Create the bv:cookies meta element\n' +
hp_site |       "    var bvCookieConsent = document.createElement('meta');\n" +
hp_site |       "    bvCookieConsent.name = 'bv:cookies';\n" +
hp_site |       "    bvCookieConsent.content = 'true';\n" +
hp_site |       '\n' +
hp_site |       '    // Append it to the head of the page\n' +
hp_site |       '    document.head.appendChild(bvCookieConsent);\n' +
hp_site |       '  }\n' +
hp_site |       '\n' +
hp_site |       "  const bvConsent = localStorage.getItem('BVConsent');\n" +
hp_site |       '\n' +
hp_site |       '  if (bvConsent) {\n' +
hp_site |       '    createBVMeta();\n' +
hp_site |       '  }\n' +
hp_site |       '\n' +
hp_site |       '  // Uercentrics "consent event", read more at https://docs.usercentrics.com/#/v2-events\n' +
hp_site |       "  window.addEventListener('ucConsentEvent', function(e) {\n" +
hp_site |       "    if (e.detail && e.detail.event == 'consent_status') {\n" +
hp_site |       `      var bvCookieConsent = document.querySelector('meta[name="bv:cookies"]');\n` +
hp_site |       '\n' +
hp_site |       '      // Check for consent status for service BazaarVoice\n' +
hp_site |       "      if (e.detail['BazaarVoice'] === true) {\n" +
hp_site |       '        if (bvCookieConsent) {\n' +
hp_site |       "          bvCookieConsent.content = 'true';\n" +
hp_site |       '        } else {\n' +
hp_site |       '            createBVMeta();\n' +
hp_site |       '        }\n' +
hp_site |       '\n' +
hp_site |       "        localStorage.setItem('BVConsent', 'true');\n" +
hp_site |       '      } else {\n' +
hp_site |       "        localStorage.removeItem('BVConsent');\n" +
hp_site |       '        // Revoke cookies consent\n' +
hp_site |       '        if (bvCookieConsent) {\n' +
hp_site |       "          bvCookieConsent.content = 'false';\n" +
hp_site |       '        }\n' +
hp_site |       '      }\n' +
hp_site |       '    }\n' +
hp_site |       '  });\n' +
hp_site |       '</script>\n' +
hp_site |       '\n' +
hp_site |       '<!-- Google Tag Manager (dataLayer) -->\n' +
hp_site |       '<script>\n' +
hp_site |       '  \n' +
hp_site |       '      dataLayer = [];\n' +
hp_site |       '    </script>\n' +
hp_site |       '<!-- Google Tag Manager -->\n' +
hp_site |       '  <script type="text/plain" data-usercentrics="Google Tag Manager">\n' +
hp_site |       "    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\n" +
hp_site |       "    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\n" +
hp_site |       "    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n" +
hp_site |       "    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n" +
hp_site |       "    })(window,document,'script','dataLayer','GTM-K5W4JQJ');\n" +
hp_site |       '  </script>\n' +
hp_site |       '</head>\n' +
hp_site |       '  <body class="error-layout">\n' +
hp_site |       '    <!-- Google Tag Manager (noscript) -->\n' +
hp_site |       '  <noscript>\n' +
hp_site |       '    <iframe\n' +
hp_site |       '      src="https://www.googletagmanager.com/ns.html?id=GTM-K5W4JQJ"\n' +
hp_site |       '      height="0"\n' +
hp_site |       '      width="0"\n' +
hp_site |       '      style="display:none;visibility:hidden"\n' +
hp_site |       '    ></iframe>\n' +
hp_site |       '  </noscript>\n' +
hp_site |       '<div id="vue-app">\n' +
hp_site |       '      <header class="mu-header mu-header--error">\n' +
hp_site |       '        <div class="mu-header__wrapper">\n' +
hp_site |       '          <div class="mu-header__main-part mu-header__main-part--error">\n' +
hp_site |       '            <a class="mu-header__logo-link eClick" href="/" data-value="Logo" data-action="Logo_klick" title="Zur Startseite von Müller Österreich">\n' +
hp_site |       '              <img\n' +
hp_site |       '                class="mu-header__logo"\n' +
hp_site |       '                src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/logo.svg"\n' +
hp_site |       '                width="110"\n' +
hp_site |       '                height="22"\n' +
hp_site |       '                alt="Müller Online Drogerie"\n' +
hp_site |       '              />\n' +
hp_site |       '            </a>\n' +
hp_site |       '            <div class="mu-header__search-slot mu-header__search-slot--error">\n' +
hp_site |       '              <search-autosuggest></search-autosuggest>\n' +
hp_site |       '  \n' +
hp_site |       '  </div>\n' +
hp_site |       '          </div>\n' +
hp_site |       '        </div>\n' +
hp_site |       '      </header>\n' +
hp_site |       '      <div class="mu-err-page">\n' +
hp_site |       '        <div class="mu-err-page__content">\n' +
hp_site |       '          <h1 class="mu-err-page__headline">Entschuldigung</h1>\n' +
hp_site |       '          <h2 class="mu-err-page__subheadline">Die aufgerufene Seite konnte leider nicht gefunden werden</h2>\n' +
hp_site |       '          <p class="mu-err-page__text">\n' +
hp_site |       '            Bitte benutzen Sie unsere Suchfunktion oder wählen Sie aus, in welcher Kategorie Sie shoppen möchten und entdecken Sie tolle Angebote.</p>\n' +
hp_site |       '          <a href="/"\n' +
hp_site |       '    class="mu-err-page__button | mu-button mu-button--type_alternative"\n' +
hp_site |       '    \n' +
hp_site |       '>\n' +
hp_site |       '    <span class="mu-button__text mu-button__text--alternative">Startseite</span>\n' +
hp_site |       '            <icon class="mu-button__arrow mu-button__arrow--alternative" icon="arrow-right"></icon></a>\n' +
hp_site |       '<div\n' +
hp_site |       '            class="mu-err-page__categories | mu-html-teaser"\n' +
hp_site |       '            style="display: none;"\n' +
hp_site |       '          >\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/parfuemerie/" rel="noopener" title="Parfümerie"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/parfum.png">Parfümerie</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/naturshop/" rel="noopener" title="Naturshop"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/naturshop.png">Naturshop</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/drogerie/" rel="noopener" title="Drogerie"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/drogerie.png">Drogerie</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/spielwaren/" rel="noopener" title="Spielwaren"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/spielwaren.png">Spielwaren</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/multi-media/" rel="noopener" title="Multi-Media"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/multimedia.png">Multi-Media</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/haushalt/" rel="noopener" title="Haushalt"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/haushalt.png">Haushalt</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/schreibwaren/" rel="noopener" title="Schreibwaren"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/schreibware.png">Schreibwaren</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/struempfe/" rel="noopener" title="Strümpfe"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/struempfe.png">Strümpfe</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/handarbeit/" rel="noopener" title="Handarbeit"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/handarbeit.png">Handarbeit</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '            <div class="mu-err-page__category | mu-image-navigation-link">\n' +
hp_site |       '              <a href="/buecher/" rel="noopener" title="Bücher"><img src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/category/buecher.png">Bücher</a>\n' +
hp_site |       '            </div>\n' +
hp_site |       '          </div>\n' +
hp_site |       '        </div>\n' +
hp_site |       '      </div>\n' +
hp_site |       '      <div class="mu-footer mu-footer--type_small">\n' +
hp_site |       '        <div class="mu-footer__wrapper">\n' +
hp_site |       '          <div class="mu-footer__columns mu-footer__columns--border-top">\n' +
hp_site |       '            <div class="mu-footer__column mu-footer__column--width_100">\n' +
hp_site |       '              <img\n' +
hp_site |       '                class="mu-footer__logo"\n' +
hp_site |       '                alt="Müller Online Drogerie"\n' +
hp_site |       '                width="25"\n' +
hp_site |       '                height="25"\n' +
hp_site |       '                src="https://static.mueller.de/716b060425ff08eafeee4dc8252169cdb3297732/assets/base/images/logotype.svg"\n' +
hp_site |       '              />\n' +
hp_site |       '              <span class="mu-footer__text mu-footer__text--copy">&copy; 2023 Müller Handels GmbH &amp; Co. KG / ÖKO-Kontrollstellen-Code: DE-ÖKO-006</span>\n' +
hp_site |       '            </div>\n' +
hp_site |       '          </div>\n' +
hp_site |       '        </div>\n' +
hp_site |       ' '... 42519 more characters
hp_site |   }
hp_site | }
```

**Comment by tiefenb** [comment]
I will take a look at this at evening

Mario Zechner ***@***.***> schrieb am Do., 29. Juni 2023,
17:07:

**Comment by tiefenb** [comment]
Looks better now after your backoff additions. Maybe there was also some problems because "https://www.mueller.at/genusswelt/aktionen/?ajax=true&p=1" category has zero products

**Pull request merged**
