### PR TITLE
Add responsive tables

### PR DESCRIPTION
**Pull request by iantsch**
Allow the collapsing of tables into datalists

image
image

### CODE REVIEW

**Comment by badlogic** [comment]
Oh god, I'm so sorry you have to dive through my terrible front end shit. You're the hero we need and don't deserve.

**Comment by badlogic** [comment]
Oh no

Screenshot 2023-05-26 at 15 58 10

**Comment by iantsch** [comment]
do you have some steps to reproduce

**Comment by iantsch** [comment]
Will be fixed with #28

**Pull request merged**
