### PR TITLE
Unimarkt Categories

### PR DESCRIPTION
**Pull request by tiefenb**
Works localy at my machine... I hope so at your's ;-D

### CODE REVIEW

**Comment by badlogic** [comment]
Super cool! I fixed up some of the mappings, everything else looks great. Do you want to fix them up in your PR?

**Comment by tiefenb** [comment]
Which fixes? I don't see any :(

**Comment by badlogic** [comment]
Screenshot 2023-06-24 at 20 44 20

Weird. I'll pull this in tonight and fix up the few categories mismappings.

**Comment by badlogic** [comment]
Latest commit has fixes. Thanks!

**Pull request merged**
